### ISSUE TITLE
Tasks - Milestone 3/16

### ISSUE THREAD

**Issue by ruchad** [FearlessApp/Fearless#29]
@haishmg @hermantai 
- [x] 1. Monitor Activity - ZoomIn or ZoomOut to show both current location and destination  - Harish
- [x] 2. Monitor Activity - Marker for current location - Harish
- [x] 3. Monitor Activity - Map user location's line - Harish
- [x] 4. Monitor Activity - Call button backend - Rucha
- [x] 5. Navigation Drawer - Shows the same trip multiple times - Herman (done, cannot reproduce it but I think https://github.com/FearlessApp/Fearless/commit/ece63ee0fde39e8a9a47f7c222ef41e95cabd1db solved it)
- [x] 6. Shake Detection message is not shown in chat  - Save the message in Trip/Parse - Rucha
- [x] 7. Fix phone number issues - Harish (Herman: no idea how to reproduce this, seems impossible from reading the code. Please debug at MainActivity this line if you can reproduce it: mPhoneNumber = StringUtil.cleanPhoneNumber(tMgr.getLine1Number());)
- [x] 8. Notify watchers when creator is not active for sometime - Harish 
- [x] 9. Startup Receiver - start sensor, start background location updater - Rucha/Harish 
- [x] 10. Remove back stack after AddWatchers - Herman
- [x] 11. Navigation Drawer - Create a Trip  - Rucha
- [x] 12. Notifications (except GotIt- works) for Trip should open that trip's Monitor Fragment. - Herman (I tried custom message and "freaking out", clicking on the notification can bring the monitor activity to the correct trip, cannot reproduce the error)
- [x] 13. Only creator should be able to complete the trip - Rucha
- [x] 14. When Trip is completed  - Rucha/Harish/Herman
   - [x] stop shake detection
   - [x] location updates
   - [x] speed detection
   - [x]  Refresh trips/ Update the trips in memory 
   - [x] send notification indicating that the trip is complete (moved)
   - [x] remove sticky notification from the creator screen 
- [x] 15. Phone number to User contact name mapping - Rucha
- [x] 16. Monitor Activity - Show watchers in toolbar. - Rucha 
- [x] 17. Monitor Activity - Add watcher - Rucha
- [x] 18. Navigation Drawer - Setting/ About -Rucha
 
Optional
- [x] Headphone jack detection - Herman
- [x] Remove MainActivity - Herman
- [ ] User should have the option to disable all the sensors  (optional, moved to https://github.com/FearlessApp/Fearless/issues/31)

From previous UI issue: https://github.com/FearlessApp/Fearless/issues/22

Start Activity (Harish)
Start Button 
[x] 1. Hide the button until destination is selected 
[x] 2. make the width match_parent
Map
[x]1. Make it same as Lyft (moved to another milestone)

Add Watchers (Rucha)
[x] Move search box at top (not doing this)
[ ] In addwatchers, can we select a contact by clicking everywhere (moved to https://github.com/FearlessApp/Fearless/issues/31)

Chat Fragment (Herman)
[x] 1. make the width match_parent 
[x] 2. Add user profile pic
[x] 3. Show Keyboard when chat fragment is created
[x] 4. Add title and watchers (use MonitorActivity)
[x] 5. Back button 

Monitor/Compose (Herman) 
[x] 1. Add color to EditText (not sure about this item)

Monitor Activity (Harish)
[x] - Avatar and start end line for creator's trip(moved to https://github.com/FearlessApp/Fearless/issues/31)

[x] When you complete trip, we need to send a chat message (moved to https://github.com/FearlessApp/Fearless/issues/31)

 [x] Need a date in the navigation drawer apart from your trip (completed)
