### ISSUE TITLE
Known Issues and UI Fixes - Milestone 3/23

### ISSUE THREAD

**Issue by ruchad** [FearlessApp/Fearless#31]
- [ ] Disable menu options 'Show Permanent Notification', 'Add Watchers' and 'Complete Trip' for the trips that are completed. 
- [ ] Add Watchers - Click anywhere on the item to select a contact

**Comment by ruchad** [comment]
- [ ] Start Activity - Clearing the destination has no effect and user can still start the trip - harish
- [ ] Shake Detection is stopped when app is destroyed - rucha
