### ISSUE TITLE
UI - Milestone 3/23

### ISSUE THREAD

**Issue by ruchad** [FearlessApp/Fearless#33]
- [x] App Launcher Icon
- [x] App Theme Color 
- [x] Transitions from create to monitor 
- [x] Change 'Watchers' to 'Friends'
- [x] Icons for - Call, Edit Watchers , Sticky Notification etc - set of icons from same source
- [x] Style the chat message 
Divider between title and messages
Padding between messages
- [x] Chat compose edit text background white border etc 
- [x] Maps - Polyline, markers, beacon icon
- [x] Icon/Button to locate creator
- [x] AddWatchersActivity, friends at the bottom should have different text size and maybe font
- [x] AddWatchersActivity, background color should be fixed
